name       : appstream-glib
version    : 0.6.12
release    : 6
source     :
    - https://people.freedesktop.org/~hughsient/appstream-glib/releases/appstream-glib-0.6.12.tar.xz : ef91b3c71fc51dc002218f149cad108abc3d57f9b4a959870224e9256aa62d58
license    : LGPL-2.1
component  : desktop.core
summary    : This library provides objects and helper methods to help reading and writing AppStream metadata.
description: |
    This library provides objects and helper methods to help reading and writing AppStream metadata.
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(libarchive)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(sqlite3)
    - pkgconfig(freetype2)
    - pkgconfig(fontconfig)
    - pkgconfig(libgcab-1.0)
    - pkgconfig(json-glib-1.0)
    - gperf
    - autoconf-archive
rundeps    :
    - gcab
patterns   :
    - devel : /usr/share/aclocal
setup      : |
    # Solus support.
    %patch -p1 < $pkgfiles/0001-builder-Implement-support-for-Solus-.eopkg-format.patch
    %patch -p1 < $pkgfiles/0002-eopkg-Enable-comparison-by-release-field-highest-win.patch
    autoreconf -vfi
    %configure --disable-static --disable-dep11 --enable-eopkg
build      : |
    %make
install    : |
    %make_install
